yatube/about/urls.py
from django.urls import path
from . import views


app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthor.as_view(), name="author"),
    path("tech/", views.AboutTech.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("create/", views.post_create, name="post_create"),
    path("posts/<post_id>/edit/", views.post_edit, name="post_edit"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
    path("posts/<post_id>/delete/", views.post_delete, name="post_delete"),
    path("posts/<post_id>/comment/", views.add_comment, name="add_comment"),
    path("group/<slug:slug>/", views.group_posts, name="group_posts"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<post_id>/", views.post_detail, name="post_detail"),
    path("follow/", views.follow_index, name="follow_index"),
    path("", views.index, name="index"),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("django.contrib.auth.urls")),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

if settings.DEBUG:
    #import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    #urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name="Название",
    )
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(
        verbose_name="Описание",
    )

    class Meta:
        verbose_name = "Сообщество"
        verbose_name_plural = "Сообщества"

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name="Текст поста", help_text="Текст нового поста"
    )
    pub_date = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата публикации"
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="Группа",
        help_text="Группа, к которой будет относиться пост",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор",
    )
    image = models.ImageField("Картинка", upload_to="posts/", blank=True)

    class Meta:
        ordering = ["-pub_date"]
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def __str__(self):
        return self.text


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Комментарий",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Автор комментария",
    )
    text = models.TextField(
        verbose_name="Комментарий", help_text="Введите текст комментария"
    )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата публикации"
    )

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"
        ordering = ("-created",)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Подписчик",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Автор поста",
    )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image")
        labels = {"text": "Текст поста", "group": "Сообщество"}

    def clean_text(self):
        data = self.cleaned_data["text"]
        if not data:
            raise forms.ValidationError("Наличие поста обязательно!")
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        labels = {"text": "Текст комментария"}

yatube/posts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .models import Post, Group, Comment, Follow, User
from .forms import PostForm, CommentForm
from django.conf import settings


def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, settings.PER_PAGE_COUNT)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    template = "posts/index.html"
    context = {
        "posts": posts,
        "page_obj": page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.post_set.all()
    paginator = Paginator(posts, settings.PER_PAGE_COUNT)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "group": group,
        "posts": posts,
        "page_obj": page_obj,
    }
    return render(request, "posts/group_list.html", context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, settings.PER_PAGE_COUNT)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )
    context = {
        "posts": posts,
        "page_obj": page_obj,
        "author": author,
        "following": following,
    }
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    posts = get_object_or_404(Post, pk=post_id)
    counter = Post.objects.filter(author=posts.author)
    form = CommentForm()
    comments = Comment.objects.filter(post_id=post_id)
    context = {
        "form": form,
        "comments": comments,
        "counter": counter,
        "posts": posts,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    template = "posts/post_create.html"
    group_choice = Group.objects.all().order_by("title")
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", username=post.author)
    context = {
        "form": form,
        "group_choice": group_choice,
        "title": "Новый пост",
        "btn_text": "Добавить",
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    is_edit = True
    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=post
    )
    if post.author == request.user and form.is_valid():
        post = form.save()
        post.save()
        return redirect("posts:post_detail", post_id=post.pk)
    context = {
        "post": post,
        "form": form,
        "is_edit": is_edit,
    }
    return render(request, "posts/post_create.html", context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, settings.PER_PAGE_COUNT)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect("posts:profile", username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    user = User(request.user.id)
    Follow.objects.filter(user=user, author=author).delete()
    return redirect("posts:profile", username)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:
        Post.objects.filter(pk=post_id).delete()
    return redirect("posts:index")

yatube/templates/posts/comment.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' posts.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% block title %}Избранные авторы{% endblock %}
  {% block content %}
  {% include 'posts/includes/switcher.html' %}
  <div class="container py-5">  
    <h1>Избранные авторы</h1>
    {%if page_obj%}
      {% for post in page_obj %}
        <article>
          {% include 'includes/post_feed_card.html' %}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
            {% if post.group %}
              <a href="{% url 'posts:group_posts' post.group.slug %}"> все записи группы {{ post.group }}</a>
            {% endif %}
            <br>
            <a href="{% url 'posts:post_detail' post.pk %}">
              Подробнее
            </a>
            <br>
        </article>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    {% else %}
      <p>Нет активных подписок</p>
    {%endif%}
    </div>
  {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Записи сообщества {{ group }}{% endblock %}    
{% block content %}
<div class="container py-5">
  <h1>{{group}}</h1>
  <p>{{group.description}}</p>
    {% for post in posts %}
      <article>
        {% include 'includes/post_feed_card.html' %}
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        <a href='{% url "posts:post_detail" post.pk %}'
          <p> Подробная информация </p>
        </a>
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}   
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% block title %}Последние обновления{% endblock %}
  {% block content %}
  {% cache 20 page_index page_obj.number %}
  <div class="container py-5">  
    <h1> Последние обновления на сайте </h1>
      {% for post in page_obj %}
        <article>
          {% include 'includes/post_feed_card.html' %}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
            {% if post.group %}
              <a href="{% url 'posts:group_posts' post.group.slug %}"> все записи группы {{ post.group }}</a>
            {% endif %}
            <br>
            <a href="{% url 'posts:post_detail' post.pk %}">
              Подробнее
            </a>
            <br>
        </article>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
  {% endcache %}
  {% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
{% if is_edit %}
  Редактировать пост
{% else %}
  Новый пост
{% endif %}{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">   
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}           
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %} 
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}        
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}           
            {% for field in form %} 
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small 
                    id="{{ field.id_for_label }}-help"
                    class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Добавить
                {% else %}
                  Сохранить
                {% endif %}               
              </button> 
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ posts|truncatechars_html:30 }}{% endblock %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ posts.pub_date }}
      </li>
      {% if posts.group %}
        <li class="list-group-item">
          Группа: {{ posts.group }}
          <a href="{% url 'posts:group_posts' posts.group.slug %}"> все записи группы</a>
        </li>
      {% endif %}
      <li class="list-group-item">
        Автор: {{ posts.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  <span >{{ counter.count }}</span>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' posts.author %}">
          Все посты пользователя
        </a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:post_edit' posts.pk %}">
          Редактировать запись
        </a>
      </li>
      {% if posts.author == user %}
        <a href="{% url 'posts:post_delete' posts.pk %}">
          <button type="button" class="btn btn-danger btn-lg btn-block">Удалить запись</button>
        </a>
      {% endif %}
    </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail posts.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ posts }}
      </p>
      <p>{% include 'posts/comment.html' %}</p>
    </article>
</div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Профиль пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
<div class="container py-5">    
  <h1>Все посты пользователя {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ posts.count }} </h3>
  {% include 'posts/includes/follow_button.html' %}
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        <a href='{% url "posts:post_detail" post.pk %}'
          <p> Подробная информация </p>
        </a>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}"> все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
</div> 
{% endblock %}